#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROS_DISTRO="${ROS_DISTRO:-jazzy}"
VENV_DIR="${OMNI_VENV:-${PROJECT_DIR}/.venv_ros}"

restore_nounset=0
case "$-" in
  *u*)
    restore_nounset=1
    set +u
    ;;
esac

source "/opt/ros/${ROS_DISTRO}/setup.bash"
if [[ -f "${VENV_DIR}/bin/activate" ]]; then
  # Build Python ROS packages with the same venv that will run them.
  source "${VENV_DIR}/bin/activate"
fi

if [[ "${restore_nounset}" -eq 1 ]]; then
  set -u
fi

cd "${PROJECT_DIR}/src/ros2_ws"

if [[ -f omni.repos && ! -d src/sllidar_ros2 ]]; then
  vcs import src < omni.repos
fi

colcon build --symlink-install

repair_omni_bridge_install() {
  local package_name=omni_bridge
  local package_src="${PROJECT_DIR}/src/ros2_ws/src/${package_name}"
  local package_prefix="${PROJECT_DIR}/src/ros2_ws/install/${package_name}"
  local package_share="${package_prefix}/share/${package_name}"
  local hook_dir="${package_share}/hook"

  if [[ ! -d "${package_prefix}" ]]; then
    echo "WARNING: ${package_name} install prefix is missing: ${package_prefix}" >&2
    return 0
  fi

  install -d \
    "${package_prefix}/share/ament_index/resource_index/packages" \
    "${package_share}/config" \
    "${package_share}/launch" \
    "${hook_dir}"

  : > "${package_prefix}/share/ament_index/resource_index/packages/${package_name}"
  install -m 0644 "${package_src}/package.xml" "${package_share}/package.xml"
  install -m 0644 "${package_src}"/config/*.yaml "${package_share}/config/"
  install -m 0644 "${package_src}"/launch/*.launch.py "${package_share}/launch/"

  cat > "${hook_dir}/ament_prefix_path.sh" <<'HOOK_SH'
# generated by install/build-workspace.sh repair_omni_bridge_install
_colcon_prepend_unique_value AMENT_PREFIX_PATH "$COLCON_CURRENT_PREFIX"
HOOK_SH

  cat > "${hook_dir}/ament_prefix_path.dsv" <<'HOOK_DSV'
prepend-non-duplicate;AMENT_PREFIX_PATH;
HOOK_DSV

  if ! grep -q 'hook/ament_prefix_path.sh' "${package_share}/package.sh"; then
    sed -i \
      '/# source sh hooks/a _colcon_package_sh_source_script "$COLCON_CURRENT_PREFIX/share/omni_bridge/hook/ament_prefix_path.sh"' \
      "${package_share}/package.sh"
  fi

  if ! grep -q 'hook/ament_prefix_path.dsv' "${package_share}/package.dsv"; then
    sed -i '1isource;share/omni_bridge/hook/ament_prefix_path.dsv' "${package_share}/package.dsv"
  fi
}

repair_omni_bridge_install
